apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-latitude-campaigns-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-latitude-prod
    kind: SecretStore
  target:
    name: goapp-dev
    creationPolicy: Owner
  dataFrom: 
#    - find: #will return every secret from dev/ folder 
#        path: latitude-campaigns/stg
    - extract:
        key: latitude-campaigns/prod