apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-goapp-dev
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: aws-goapp-dev
    kind: SecretStore
  target:
    name: goapp-dev
    creationPolicy: Owner
  data:
  - secretKey: aws-goapp-dev