apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: external-secret-role
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      # optional: do a sts:assumeRole before fetching secrets
      role: external-secret-role
